export const CREATING_SETLIST = 'CREATING_SETLIST';
export const CREATING_SETLIST_SUCCESS = 'CREATING_SETLIST_SUCCESS';
export const CREATING_SETLIST_ERR = 'CREATING_SETLIST_ERR';
export const FETCH_SETLISTS = 'FETCH_SETLISTS';
