export const FETCH_SETLIST = 'FETCH_SETLIST';
export const ADD_SETLIST_SONG = 'ADD_SETLIST_SONG';
export const SAVE_SETLIST_SONG = 'SAVE_SETLIST_SONG';
export const DELETE_SETLIST_SONG = 'DELETE_SETLIST_SONG';
export const SAVE_SETLIST_SONGS_SORT = 'SAVE_SETLIST_SONGS_SORT';
